### PR TITLE
signature checks didn't work

### PR DESCRIPTION
**Pull request by mrbasil**

### CODE REVIEW

**Comment by pitbulk** [comment]
Nice catch

**Comment by pitbulk** [comment]
Released [1.2.1](https://pypi.python.org/pypi/python3-saml/1.2.1)

Let me know if you experience any other issue.

**Comment by jgehrcke** [comment]
@pitbulk what needs to be done so that the issue that was fixed here is covered by the unit tests?

**Comment by pitbulk** [comment]
At [response_test.py](https://github.com/onelogin/python3-saml/blob/master/tests/src/OneLogin/saml2_tests/response_test.py) we should create the methods:
-1. testSignatureWantAssertionsSigned
-2. testSignatureWantMessagesSigned

Both should have as input 2 valid SAMLResponse [One with only assertion signed](https://github.com/onelogin/python3-saml/blob/master/tests/data/responses/signed_assertion_response2.xml.base64), [other with all message signed](https://github.com/onelogin/python3-saml/blob/master/tests/data/responses/valid_response.xml.base64), and with strict mode enabled.

testSignatureWantAssertionsSigned
- With wantAssertionsSigned disabled both responses must be consider valid
- With wantAssertionsSigned enabled only the response with signed assertion must be consider valid

testSignatureWantMessagesSigned
- With wantMessagesSigned disabled both responses must be consider valid
- With wantMessagesSigned enabled only the response with signed whole messag signed must be consider valid

Do you want to contribute with a PR?

**Pull request merged**
