### PR TITLE
fix for issue where if there were multiple signing certs and no encry…

### PR DESCRIPTION
**Pull request by bmorgan21**
…ption certs, only the first signing cert is returned

### CODE REVIEW

**Comment by pitbulk** [comment]
Can you provide test so we assure we don't break in the future?

**Comment by bmorgan21** [comment]
yes, just figuring out the environment.  Once the tests pass, I will update the tests.

**Comment by bmorgan21** [comment]
@pitbulk this PR should be ready for you to take a look!

**Comment by bmorgan21** [comment]
Anything else needed here to get this merged and to make a patch release?

**Pull request merged**
