### PR TITLE
Add get_last_message_id and get_last_assertion_id

### LINKED ISSUE #62: Api to extract response ids?
What is the recommended method to detect and stop replay attacts in the IdP initiated scenario?

My initial idea was to persist all previously seen Response and Assertion ids ignore responses that contain preciously seen Response or Assertion ids. Unfortunately I've not been able to find any good way to extract these ids from the response. They seem to be added to a local variable called "verified_ids" but there is no way to access it.

### PR DESCRIPTION
**Pull request by jborg**
I tried to follow the pattern used in php-saml.

This is an attempt to fix #62

### CODE REVIEW

**Comment by pitbulk** [comment]
I will review and merge asap

**Comment by jborg** [comment]
Have you had any chance to look at this?

**Comment by pitbulk** [comment]
Sorry I will review it tomorrow as well as other issues and release a new version.

**Comment by pitbulk** [comment]
I gonna merge it now and add some more test as well as support for getLastAssertionNotOnOrAfter

**Pull request merged**
