### PR TITLE
Add a Pyramid demo.

### PR DESCRIPTION
**Pull request by charlescbeebe**
Add a Pyramid demo in demo_pyramid dir (generated with
'pyramid-cookiecutter-starter' Cookiecutter template).

Add 'pyramid' as a keyword in setup.py.

### CODE REVIEW

**Comment by pitbulk** [comment]
Thanks for this contribution, I will test and merge as soon as possible.

**Comment by charlescbeebe** [comment]
@pitbulk awesome, thanks! Btw, just updated the global README with instructions on how to install & run the demo.

**Comment by charlescbeebe** [comment]
@pitbulk anything I can do to help w/ this PR?

**Comment by pitbulk** [comment]
Merged, sorry for the delay.

**Comment by pitbulk** [comment]
Added also on python-saml:
https://github.com/onelogin/python-saml/commit/cebc37b67ffa440b4e0e98f5852045b7fd1b6ca3

**Pull request merged**
