### PR TITLE
Add flexibility to the slo implementation so compression isn't required.

### PR DESCRIPTION
**Pull request by jeremyschiff**
We don't currently have a way of switching off compression in SLO, please give us the flexibility. Some providers aren't compressing, and it's throwing an error and there is no way to compensate.

### CODE REVIEW

**Comment by pitbulk** [comment]
From SAML standard, [SAML bindings - 3.4.4](https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf)
```
A query string parameter named SAMLEncoding is reserved to identify the encoding mechanism used. If
this parameter is omitted, then the value is assumed to be urn:oasis:names:tc:SAML:2.0:bindings:URL-Encoding:DEFLATE.

All endpoints that support this binding MUST support the DEFLATE encoding
```

Can you share an example of what you are receiving from IdPs?

**Comment by jeremyschiff** [comment]
The IdP is Okta.  Here is my configuration:
```
{
    "strict": true,
    "debug": true,
    "sp": {
        "entityId": "http://localhost:8000/saml/metadata",
        "assertionConsumerService": {
            "url": "http://localhost:8000/saml/external/acs",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
        "singleLogoutService": {
            "url": "http://localhost:8000/saml/external/sls",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
        "x509cert": <Redacted>,
        "privateKey": <Redacted>
    },
    "idp": {
        "entityId": "http://www.okta.com/<Redacted>",
        "singleSignOnService": {
            "url": "https://<Redacted>.oktapreview.com/app/<Redacted>/sso/saml",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "singleLogoutService": {
            "url": "https://<Redacted>.oktapreview.com/app/<Redacted>/slo/saml",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "x509cert": <Redacted>
    }
}

```
Here is the req object:
`{'https': 'off', 'http_host': 'localhost', 'script_name': '/saml/external/sls', 'server_port': '8000', 'get_data': <QueryDict: {}>, 'post_data': <QueryDict: {'SAMLResponse': ['<Redacted (encoded, but not compressed)>'], 'RelayState': ['http://localhost:8000/backend/saml/logout']}>}
`

I have reviewed the documentation in Okta, and it has mentioned a challenge in that the response is in the POST body, not the get body.  That was easily handled by setting the 'get_data' to be 'post_data', but it's still trying to decompress the response, which was why I requested these additional flags (so I can prevent the assert in utils.decode_base64_and_inflate from triggering and not being protected.  

I'm glad to use any solution that resolves the problem.  Where would the SAMLEncoding parameter be specified?  It doesn't seem that one is set.

**Comment by pitbulk** [comment]
I see

On HTTP-POST binding, the data is not compressed.
But you are tricking the toolkit by injecting the POST data into the GET.

I will do the toolkit flexible and no raise an error when data is not compressed.

**Comment by jeremyschiff** [comment]
After this discussion, the other option is you to check the POST if it's not in the GET.  This seems slightly better, as I won't have to "trick" the toolkit at all.  I presume that's easy to do?

**Pull request closed without merging**
